### ISSUE TITLE
[Bug report]: Windows nodejs global path contains spaces.

### ISSUE THREAD

**Issue by scccboom** [avwo/set-global-proxy#1]
OS: Windows 10
Node: v16.15.1
npm: 8.11.0

Error in executing command.
```
w2 proxy
```
> 'C:\Program' is not recognized as an internal or external command

My sulotion

```js
//: lib/win/index.js:5
var REFRESH_PROXY = JSON.stringify(join(__dirname, 'refresh'));
```

**Comment by avwo** [comment]
重新安装 whistle 试试
