### ISSUE TITLE
Can you submit the source code of the binary files that set up the system proxy for mac and windows?

### ISSUE THREAD

**Issue by Junyan** [avwo/set-global-proxy#3]
Since these are compiled binary files, I want to understand how they are implemented.

**Comment by avwo** [comment]
https://github.com/alibaba/lightproxy/tree/master/vendor/proxy_conf_helper
https://github.com/alibaba/lightproxy/tree/master/vendor/win_proxy_helper

**Comment by Junyan** [comment]
thanks
